name: dispatch-workflows-on-pr-labeled

on:
  pull_request:
    types:
      - labeled

permissions:
  actions: write

jobs:
  dispatch_workflow1:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'workflow1'
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: workflow1.yml
          ref: ${{ github.event.pull_request.head.ref }}
          inputs: |
            { 
              "message": "blah blah"
            }

  dispatch_workflow2:
    runs-on: ubuntu-latest
    if: github.event.label.name == 'workflow2'
    steps:
      - uses: benc-uk/workflow-dispatch@v1
        with:
          workflow: workflow2.yml
          ref: ${{ github.event.pull_request.head.ref }}
          inputs: |
            { 
              "message": "blah blah"
            }
