name: workflow2

on:
  workflow_dispatch:
    inputs:
      message:
        type: string
        default: ''
        description: ''

jobs:
  workflow1:
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo "${{ toJson(github.event.inputs) }}"

      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@master
        if: always()
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          status: ${{ job.status }}
          context: CI workflow2
